'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Check, Download, Send, ShieldCheck, Sparkles } from 'lucide-react';

const KEY = 'afterimage:memories:v2';
type Memory = { id: string; text: string; trigger?: string; why?: string; mode?: 'signal' | 'pattern'; state?: string; confidence?: number; resurfacedCount?: number; createdAt?: string; source?: string; sourceUrl?: string };
function normalize(input: unknown): Memory[] { if (!Array.isArray(input)) return []; return input.filter((item): item is Memory => !!item && typeof item === 'object' && typeof (item as Memory).text === 'string').map((item) => ({ ...item, id: item.id || crypto.randomUUID(), mode: item.mode || 'signal', state: item.state || 'active', confidence: typeof item.confidence === 'number' ? item.confidence : 0.7, resurfacedCount: typeof item.resurfacedCount === 'number' ? item.resurfacedCount : 0, createdAt: item.createdAt || new Date().toISOString() })); }

export default function ExtensionBridge() {
  const [incoming, setIncoming] = useState<Memory[]>([]); const [saved, setSaved] = useState(0); const [ready, setReady] = useState(false); const [prepared, setPrepared] = useState(false);
  useEffect(() => { const hash = new URLSearchParams(window.location.hash.slice(1)); const raw = hash.get('memories'); if (!raw) { setReady(true); return; } try { setIncoming(normalize(JSON.parse(decodeURIComponent(raw)))); } catch { setIncoming([]); } history.replaceState(null, '', window.location.pathname); setReady(true); }, []);
  const merge = () => { try { const existing = normalize(JSON.parse(localStorage.getItem(KEY) || '[]')); const byId = new Map(existing.map((memory) => [memory.id, memory])); incoming.forEach((memory) => byId.set(memory.id, { ...byId.get(memory.id), ...memory })); localStorage.setItem(KEY, JSON.stringify([...byId.values()].slice(0, 300))); setSaved(incoming.length); } catch { setSaved(0); } };
  const exportMemories = () => { const memories = normalize(JSON.parse(localStorage.getItem(KEY) || '[]')); const blob = new Blob([JSON.stringify(memories, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'afterimage-memories.json'; a.click(); URL.revokeObjectURL(url); };
  const prepareForExtension = () => { try { const memories = normalize(JSON.parse(localStorage.getItem(KEY) || '[]')).slice(0, 100); if (!memories.length) { setPrepared(false); return; } const payload = encodeURIComponent(JSON.stringify(memories)); history.replaceState(null, '', `${window.location.pathname}#export=${payload}`); setPrepared(true); } catch { setPrepared(false); } };
  const countLabel = useMemo(() => incoming.length === 1 ? '1 browser memory' : `${incoming.length} browser memories`, [incoming.length]);
  return <main className="shell" style={{minHeight:'100vh',padding:'42px 24px'}}><section className="hero" style={{maxWidth:860,margin:'0 auto'}}><Link href="/" className="navlink"><ArrowLeft size={14}/> Back to Afterimage</Link><div className="eyebrow" style={{marginTop:30}}><span className="pulse"/> EXTENSION BRIDGE</div><h1>One memory system.<br/><em>Every surface.</em></h1><p className="lede">Move memories between the browser extension and your main Afterimage library without a server.</p><div className="capture" style={{marginTop:28}}><div className="capture-top"><span><Sparkles size={15}/> Browser ↔ Afterimage</span><span className="hint">Local handoff</span></div>{!ready ? <p>Reading the local handoff…</p> : incoming.length === 0 ? <div className="empty-match"><span>READY</span><b>Use the extension to send browser memories here, or prepare this library for the extension.</b><p>No memory transfer happens until you explicitly choose a bridge action.</p></div> : <><div className="preview" role="status"><div className="preview-icon"><ShieldCheck size={18}/></div><div><b>{countLabel} ready.</b><p>They will be merged with your existing Afterimage library. Existing IDs are updated rather than duplicated.</p></div></div><div className="match-actions"><button className="create-memory" onClick={merge}><Check size={14}/> Merge into Memory library</button><button className="export" onClick={exportMemories}><Download size={14}/> Export current library</button></div>{saved>0&&<div className="preview" role="status"><b>{saved} browser memories merged.</b><p>Open Memory Vault or Future Self to continue managing them.</p></div>}</>}</div><div className="capture" style={{marginTop:18}}><div className="capture-top"><span><Send size={15}/> Afterimage → Extension</span><span className="hint">Explicit only</span></div><p>Prepare up to 100 current memories in this page's URL fragment. Then open the extension popup and choose <b>Import Afterimage memories</b>.</p><button className="create-memory" onClick={prepareForExtension}><Send size={14}/> Prepare for extension</button>{prepared&&<div className="preview" role="status"><b>Library prepared.</b><p>Keep this tab open, open the Afterimage extension, and press Import Afterimage memories.</p></div>}</div><div className="grid" style={{marginTop:24}}><Feature title="One library" body="Both directions merge by memory ID, so browser captures and main-app memories stay aligned without duplicate records."/><Feature title="Explicit handoff" body="Nothing is transferred in the background. You initiate every browser ↔ app handoff."/><Feature title="Portable" body="The library can still be exported as JSON for backup or migration."/></div></section></main>;
}
function Feature({title,body}:{title:string;body:string}) { return <article className="feature"><h3>{title}</h3><p>{body}</p></article>; }
