'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import Link from 'next/link';
import { ArrowRight, BellRing, Brain, Check, Clock3, Compass, Download, FlaskConical, LockKeyhole, RotateCcw, Search, Settings2, Sparkles, Trash2, X } from 'lucide-react';
import { ContextMatch, ContextMemory, MemoryState, matchContext, markResurfaced, snoozeMemory } from '../lib/context-engine';
import { normalizePreferences } from '../lib/context-signals';

type Memory = ContextMemory;
const STORAGE_KEY = 'afterimage:memories:v2';
const PREF_KEY = 'afterimage:signal-preferences:v1';
const examples = [
  { text: 'I keep forgetting why I chose the cheaper hosting plan.', tag: 'decision', when: 'When you compare hosting again' },
  { text: 'If I am still avoiding this task tomorrow, show me the smallest next move.', tag: 'moment', when: 'Tomorrow at 9:00' },
  { text: 'Before I buy another keyboard, remind me I already own two.', tag: 'pattern', when: 'Next time I shop for keyboards' }
];
const simulations = ['I am comparing hosting providers and migration costs again','I am shopping for another keyboard today','I am deciding whether to switch my phone plan','I am avoiding the same task again'];

export default function Home() {
 const [input,setInput]=useState(''),[trigger,setTrigger]=useState(''),[captured,setCaptured]=useState(false),[mode,setMode]=useState<'signal'|'pattern'>('signal');
 const [memories,setMemories]=useState<Memory[]>([]),[context,setContext]=useState(''),[matches,setMatches]=useState<ContextMatch[]>([]),[selected,setSelected]=useState<ContextMatch|null>(null),[query,setQuery]=useState(''),[sensitivity,setSensitivity]=useState(.25);
 useEffect(()=>{try{const raw=localStorage.getItem(STORAGE_KEY)||localStorage.getItem('afterimage:memories:v1')||localStorage.getItem('afterimage:memories')||'[]';const saved=JSON.parse(raw);if(Array.isArray(saved))setMemories(saved.map((m:Memory)=>({...m,state:m.state||'active',confidence:m.confidence??.7,resurfacedCount:m.resurfacedCount??0})));const p=localStorage.getItem(PREF_KEY);if(p)setSensitivity(normalizePreferences(JSON.parse(p)).sensitivity)}catch{}},[]);
 const sample=useMemo(()=>input.trim()||examples[0].text,[input]);
 const visibleMemories=useMemo(()=>memories.filter(m=>{const q=query.toLowerCase().trim();return !q||`${m.text} ${m.trigger||''} ${m.mode} ${m.state||'active'}`.toLowerCase().includes(q)}),[memories,query]);
 function persist(next:Memory[]){setMemories(next);localStorage.setItem(STORAGE_KEY,JSON.stringify(next));}
 function capture(){const memory:Memory={id:crypto.randomUUID(),text:sample,mode,createdAt:new Date().toISOString(),trigger:trigger.trim()||undefined,state:'active',confidence:.8,resurfacedCount:0};persist([memory,...memories].slice(0,100));setCaptured(true);setInput('');setTrigger('');}
 function simulate(value=context){setContext(value);setMatches(matchContext(memories,value,{sensitivity}));}
 function updateMemory(id:string,patch:Partial<Memory>){const next=memories.map(m=>m.id===id?{...m,...patch}:m);persist(next);setMatches(prev=>prev.map(x=>x.memory.id===id?{...x,memory:{...x.memory,...patch}}:x));if(selected?.memory.id===id)setSelected({...selected,memory:{...selected.memory,...patch}})}
 function resurface(match:ContextMatch){const updated={...markResurfaced(match.memory),state:'confirmed' as MemoryState,confidence:Math.min(1,(match.memory.confidence??.7)+.08)};updateMemory(updated.id,updated);setSelected({...match,memory:updated});}
 function quiet(match:ContextMatch){updateMemory(match.memory.id,snoozeMemory(match.memory,30));setMatches(prev=>prev.filter(x=>x.memory.id!==match.memory.id));setSelected(null)}
 function state(id:string,value:MemoryState){updateMemory(id,{state:value})}
 function exportMemories(){const blob=new Blob([JSON.stringify(memories,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='afterimage-memories.json';a.click();URL.revokeObjectURL(url)}
 function clearMemories(){persist([]);setMatches([]);setSelected(null);localStorage.removeItem('afterimage:memories:v1');localStorage.removeItem('afterimage:memories')}
 return <main className="shell">
  <nav className="nav"><div className="brand"><span className="mark"><Sparkles size={15}/></span> AFTERIMAGE</div><div className="nav-actions"><a href="#memories" className="navlink"><Brain size={12}/> Memories</a><Link href="/context-signals" className="navlink"><Settings2 size={12}/> Context signals</Link><Link href="/graph" className="navlink"><Brain size={12}/> Memory graph</Link><span className="navlink"><LockKeyhole size={12}/> Private by design</span></div></nav>
  <section className="hero"><div className="eyebrow"><span className="pulse"/> A new kind of personal software</div><h1>Your apps remember<br/><em>the wrong things.</em></h1><p className="lede">Afterimage remembers the tiny context that matters — then waits until the moment it becomes useful again.</p>
   <div className="capture"><div className="capture-top"><span>Leave an afterimage</span><span className="hint">No lists. No streaks. No feed.</span></div><textarea aria-label="Memory for future you" value={input} onChange={e=>{setInput(e.target.value);setCaptured(false)}} placeholder="Tell future you something current-you knows…"/><div className="return-condition"><span>RETURN CONDITION</span><input aria-label="Return condition" value={trigger} onChange={e=>{setTrigger(e.target.value);setCaptured(false)}} placeholder="When should this become useful again? e.g. When you compare hosting"/></div><div className="capture-bottom"><div className="chips"><button className={mode==='signal'?'active':''} onClick={()=>setMode('signal')}><Clock3 size={14}/> Find the right moment</button><button className={mode==='pattern'?'active':''} onClick={()=>setMode('pattern')}><Compass size={14}/> Find the next pattern</button></div><button className="send" aria-label="Store afterimage" onClick={capture}>{captured?<Check size={18}/>:<ArrowRight size={18}/>}</button></div></div>
   {captured&&<div className="preview" role="status"><div className="preview-icon"><BellRing size={18}/></div><div><b>Stored with an adaptive return condition.</b><p>Memory saved for your future self.</p><small>Saved only in this browser. Nothing was sent to a server.</small></div></div>}
  </section>
  <section className="why"><div className="section-kicker">THE DIFFERENCE</div><h2>Memory that moves through time.</h2><div className="grid"><Feature icon={<Brain/>} title="Context, not reminders" body="You don't schedule a notification. You teach the app what situation should bring a memory back."/><Feature icon={<RotateCcw/>} title="It can learn to stop" body="Confirm useful memories, mark stale ones outdated, or quietly snooze a memory when it is not useful yet."/><Feature icon={<Sparkles/>} title="Your patterns become visible" body="Over time, recurring choices, unfinished intentions and forgotten reasons can become a private map."/></div></section>
  <section className="lab"><div className="section-kicker">AFTERIMAGE LAB / ADAPTIVE MEMORY</div><h2>Make the context return.</h2><p>Matching is local and explainable. Sensitivity is {Math.round(sensitivity*100)}%, so you control how selective Afterimage is.</p><div className="sim-row">{simulations.map(s=><button key={s} onClick={()=>simulate(s)}>{s}</button>)}</div><div className="sim-input"><input aria-label="Simulate current context" value={context} onChange={e=>setContext(e.target.value)} placeholder="Simulate what you are doing right now…"/><button onClick={()=>simulate()}><FlaskConical size={16}/> Match context</button></div>
   {context&&<div className="results" aria-live="polite">{matches.length===0?<div className="empty-match"><span>NO RESURFACING</span><b>Nothing looks relevant yet.</b><p>That is a feature. Afterimage stays quiet when the context does not justify a memory.</p></div>:matches.slice(0,3).map(match=><article className="match" key={match.memory.id}><div className="match-head"><span>AFTERIMAGE / {Math.round(match.score*100)}% MATCH</span><span>{(match.memory.state||'active').toUpperCase()}</span></div><p>“{match.memory.text}”</p>{match.memory.trigger&&<div className="match-trigger">RETURN CONDITION · {match.memory.trigger}</div>}<small>Why now? {match.reason}</small><div className="match-actions"><button onClick={()=>resurface(match)}><Check size={14}/> Still useful</button><button onClick={()=>quiet(match)}><Clock3 size={14}/> Quiet for 30 days</button><button onClick={()=>state(match.memory.id,'outdated')}><X size={14}/> No longer true</button><button onClick={()=>setSelected(match)}>Inspect memory</button></div></article>)}</div>}
  </section>
  <section className="demo"><div><div className="section-kicker">HOW IT FEELS</div><h2>The app disappears.<br/>The moment doesn't.</h2><p>Imagine comparing a phone plan six months from now. Instead of searching old notes, Afterimage quietly brings back what mattered last time — and lets you decide whether it still matters.</p></div><div className="timeline"><div className="node old"><span>JAN</span><b>Captured</b><p>“I chose this because switching costs hurt more than the extra ₹300.”</p></div><div className="line"/><div className="node now"><span>JUL</span><b>Context detected</b><p>You're comparing the same category again.</p></div><div className="line"/><div className="node reveal"><span>NOW</span><b>Afterimage</b><p>“Here’s what mattered to you last time.”</p></div></div></section>
  <section className="examples"><div className="section-kicker">TRY THE IDEA</div><h2>Three memories worth keeping.</h2><div className="cards">{examples.map((x,i)=><button key={i} className="example" onClick={()=>{setInput(x.text);setTrigger(x.when);setCaptured(false)}}><span className="tag">{x.tag}</span><p>{x.text}</p><small>{x.when}</small></button>)}</div></section>
  <section className="memory-wall" id="memories"><div><div className="section-kicker">YOUR MEMORIES / {memories.length}</div><h2>Memory library.</h2><p className="lede">Everything you leave for your future self stays in this browser. Search, export, archive, or mark a memory outdated.</p></div><div className="memory-tools"><div className="memory-search"><Search size={14}/><input aria-label="Search memories" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search memories…"/></div><button className="export" onClick={exportMemories}><Download size={14}/> Export</button><button className="clear" onClick={clearMemories}><Trash2 size={14}/> Clear local memories</button></div>{memories.length===0?<div className="empty-match"><span>MEMORY LIBRARY</span><b>No memories yet.</b><p>Write something for your future self above, then press the arrow. Your saved memories will appear here.</p><a href="#top" onClick={e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'})}}>↑ Leave your first afterimage</a></div>:<div className="memory-list">{visibleMemories.map(memory=><article className="memory" key={memory.id}><span>{memory.mode==='signal'?'CONTEXT':'PATTERN'} · {(memory.state||'active').toUpperCase()}</span><p>{memory.text}</p>{memory.trigger&&<small>Returns when: {memory.trigger}</small>}<small>Confidence: {Math.round((memory.confidence??.7)*100)}% · Resurfaced: {memory.resurfacedCount??0}×</small><small>Stored {new Date(memory.createdAt).toLocaleString()}</small><div className="memory-actions"><button onClick={()=>state(memory.id,memory.state==='archived'?'active':'archived')}>{memory.state==='archived'?'Restore':'Archive'}</button>{memory.state!=='outdated'&&<button onClick={()=>state(memory.id,'outdated')}>Outdated</button>}</div></article>)}</div>}</section>
  <footer><span>AFTERIMAGE / concept build 0.8</span><span>Memory → Condition → Context → Relevance → Feedback → Resurface</span></footer>
  {selected&&<div className="inspector-backdrop" onClick={()=>setSelected(null)}><aside className="inspector" onClick={e=>e.stopPropagation()}><button className="inspector-close" onClick={()=>setSelected(null)}><X size={16}/></button><div className="section-kicker">MEMORY INSPECTOR</div><h3>Why did this return?</h3><p className="inspector-memory">“{selected.memory.text}”</p>{selected.memory.trigger&&<div className="inspect-row"><span>RETURN CONDITION</span><b>{selected.memory.trigger}</b></div>}<div className="inspect-row"><span>MATCHED TERMS</span><b>{selected.matchedTerms.join(' · ')}</b></div><div className="inspect-row"><span>CONFIDENCE</span><b>{Math.round((selected.memory.confidence??.7)*100)}%</b></div><div className="inspect-row"><span>RESURFACED</span><b>{selected.memory.resurfacedCount??0} times</b></div><div className="inspect-reason">{selected.reason}</div><button className="inspector-action" onClick={()=>{resurface(selected);setSelected(null)}}><Check size={15}/> Still useful</button><button className="inspector-action" onClick={()=>quiet(selected)}><Clock3 size={15}/> Quiet for 30 days</button><button className="inspector-action" onClick={()=>{state(selected.memory.id,'archived');setSelected(null)}}><RotateCcw size={15}/> Archive memory</button><button className="inspector-action danger" onClick={()=>{state(selected.memory.id,'outdated');setSelected(null)}}><X size={15}/> This is no longer true</button></aside></div>}
 </main>
}
function Feature({icon,title,body}:{icon:ReactNode;title:string;body:string}){return <article className="feature"><div className="feature-icon">{icon}</div><h3>{title}</h3><p>{body}</p></article>}
