'use client';

import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { AlertTriangle, ArrowLeft, Archive, Check, Clock3, RefreshCw, Sparkles, X } from 'lucide-react';
import { detectContradictions, ContextMemory, type MemoryState } from '../../lib/context-engine';
import { healthReview, memoryHealth } from '../../lib/memory-health';
import { memoryTimeline } from '../../lib/memory-timeline';

type Memory = ContextMemory;
const KEY='afterimage:memories:v2';
function load():Memory[]{try{const raw=localStorage.getItem(KEY)||localStorage.getItem('afterimage:memories:v1')||'[]';const data=JSON.parse(raw);return Array.isArray(data)?data:[]}catch{return[]}}
function priority(m:Memory){const confidence=1-(m.confidence??.7);const repeats=Math.min(1,(m.resurfacedCount??0)/4);const age=Math.min(1,Math.max(0,(Date.now()-new Date(m.createdAt).getTime())/(180*86400000)));return confidence*.45+repeats*.25+age*.15+(m.sensitivity==='eager'?.05:0)}

export default function FutureSelf(){
 const [memories,setMemories]=useState<Memory[]>([]);const [selected,setSelected]=useState<Memory|null>(null);const [toast,setToast]=useState('');const [context,setContext]=useState('');
 useEffect(()=>setMemories(load()),[]);
 const active=useMemo(()=>memories.filter(m=>m.state!=='archived'&&m.state!=='outdated'),[memories]);
 const needsReview=useMemo(()=>[...active].sort((a,b)=>priority(b)-priority(a)).slice(0,6),[active]);
 const changes=useMemo(()=>context.trim()?detectContradictions(active,context):[],[active,context]);
 const healthItems=useMemo(()=>healthReview(active),[active]);
 const healthCounts=useMemo(()=>healthItems.reduce((acc,item)=>{acc[item.health]++;return acc},{fresh:0,familiar:0,fading:0,stale:0}),[healthItems]);
 const weakest=healthItems[0];
 const recent=useMemo(()=>[...active].sort((a,b)=>priority(b)-priority(a)).slice(0,6),[active]);
 const timeline=useMemo(()=>memoryTimeline(memories),[memories]);
 function save(next:Memory[]){setMemories(next);localStorage.setItem(KEY,JSON.stringify(next));}
 function act(id:string,state:MemoryState){save(memories.map(m=>m.id===id?{...m,state}:m));setSelected(null);setToast(state==='confirmed'?'Memory confirmed for future you.':state==='outdated'?'Memory marked as no longer true.':'Memory archived quietly.');setTimeout(()=>setToast(''),2600)}
 return <main className="future-page">
  <nav className="graph-nav"><Link href="/" className="graph-back"><ArrowLeft size={14}/> Back to Afterimage</Link><span className="future-nav-mark"><Sparkles size={13}/> FUTURE SELF</span></nav>
  <section className="future-hero"><div className="section-kicker">THE MEMORY LAYER FOR YOUR FUTURE SELF</div><h1>What does future-you<br/><em>need to remember?</em></h1><p>Afterimage keeps the important reasons behind your decisions close — without forcing you to schedule a reminder. Review what is still useful, what is fading, and what may have changed.</p><div className="future-actions"><Link className="future-primary" href="/#memories">+ Leave an afterimage</Link><Link className="future-secondary" href="/memory-review">Review memory health</Link></div></section>
  <section className="future-stats"><div><span>ACTIVE MEMORIES</span><b>{active.length}</b><small>Available for contextual resurfacing</small></div><div><span>NEEDS REVIEW</span><b>{needsReview.length}</b><small>Prioritized by confidence, reuse and age</small></div><div><span>MEMORY HEALTH</span><b>{healthCounts.fading+healthCounts.stale}</b><small>{healthCounts.fading} fading · {healthCounts.stale} stale</small></div></section>
  {toast&&<div className="future-toast" role="status"><Check size={15}/> {toast}</div>}
  {weakest&&<section className="future-section" style={{paddingTop:10}}><div className="section-kicker">HEALTH CHECK</div><h2>Trust, with context.</h2><div className="future-card" style={{marginTop:14}}><div className="future-card-top"><span>{weakest.health.toUpperCase()} · {Math.round(weakest.score*100)}% HEALTH</span><span>{Math.round((weakest.memory.confidence??.7)*100)}% CONFIDENCE</span></div><p className="future-quote">“{weakest.memory.text}”</p><p className="future-why">{weakest.reason}</p><div className="future-card-actions"><button onClick={()=>setSelected(weakest.memory)}><RefreshCw size={13}/> Review this memory</button><Link href="/memory-review" className="future-secondary">Open full health review</Link></div></div></section>}
  <section className="future-section"><div className="section-kicker">MEMORY TIMELINE</div><h2>See how your memories change over time.</h2><p style={{color:'var(--muted)',maxWidth:720}}>A compact local history of capture, resurfacing and feedback. Afterimage never silently rewrites an older memory.</p>{timeline.length===0?<div className="future-empty"><Sparkles size={20}/><b>Your timeline starts with your first memory.</b><p>Capture something worth preserving and its lifecycle will appear here.</p></div>:<div style={{display:'grid',gap:0,marginTop:18}}>{timeline.slice(0,12).map((event,index)=><article key={event.id} style={{display:'grid',gridTemplateColumns:'96px 22px 1fr',gap:12,alignItems:'start',paddingBottom:18}}><small style={{color:'var(--muted)',paddingTop:2}}>{new Date(event.at).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}</small><span style={{width:10,height:10,borderRadius:'50%',border:'2px solid var(--acid)',marginTop:4,boxSizing:'border-box'}}/><div><b style={{fontSize:13}}>{event.label}</b><p style={{margin:'5px 0 0',color:'var(--muted)',fontSize:13}}>{event.memory.text}</p></div></article>)}</div>}</section>
  <section className="future-section"><div className="section-kicker">CHANGE RADAR</div><h2>Check before you trust.</h2><p style={{color:'var(--muted)',maxWidth:720}}>Paste the situation you are in now. Afterimage looks for explicit change language that overlaps an older memory — locally, without sending context anywhere.</p><textarea value={context} onChange={e=>setContext(e.target.value)} placeholder="Example: I changed our hosting provider and the old deployment plan is no longer valid…" aria-label="Current context for change radar" style={{width:'100%',minHeight:110,boxSizing:'border-box',marginTop:14,padding:16,borderRadius:14,border:'1px solid var(--line)',background:'var(--panel)',color:'var(--ink)',font:'inherit'}}/>
   {changes.length>0&&<div style={{display:'grid',gap:10,marginTop:14}}>{changes.map(c=><div key={c.memory.id} style={{border:'1px solid #6a4930',borderRadius:14,padding:15,background:'rgba(120,80,30,.08)'}}><div style={{display:'flex',gap:8,alignItems:'center',fontSize:12,color:'#f0b36a'}}><AlertTriangle size={14}/> POTENTIAL CHANGE</div><p style={{margin:'9px 0'}}>{c.memory.text}</p><small style={{color:'var(--muted)'}}>{c.reason}</small><div style={{marginTop:10}}><button className="future-secondary" onClick={()=>setSelected(c.memory)}>Review memory</button></div></div>)}</div>}
  </section>
  <section className="future-section"><div className="section-kicker">FUTURE SELF INBOX</div><h2>Small clues. Better decisions.</h2>{active.length===0?<div className="future-empty"><Sparkles size={22}/><b>Your future self has nothing yet.</b><p>Leave one memory with a Return Condition. The goal is not to collect notes — it is to preserve the reason behind a decision until it matters again.</p><Link href="/#memories" className="future-primary">Create your first memory</Link></div>:<div className="future-grid">{recent.map(memory=>{const health=memoryHealth(memory);return <article className="future-card" key={memory.id}><div className="future-card-top"><span>{priority(memory)>.35?'REVIEW SOON':memory.state==='confirmed'?'CONFIRMED':'WAITING FOR CONTEXT'}</span><span>{health.health.toUpperCase()} · {Math.round(health.score*100)}% HEALTH</span></div><p className="future-quote">“{memory.text}”</p>{memory.trigger&&<div className="future-chip"><Clock3 size={12}/> {memory.trigger}</div>}{memory.why&&<p className="future-why">Why it matters: {memory.why}</p>}<div className="future-card-actions"><button onClick={()=>act(memory.id,'confirmed')}><Check size={13}/> Still true</button><button onClick={()=>setSelected(memory)}><RefreshCw size={13}/> Review</button><button onClick={()=>act(memory.id,'outdated')}><X size={13}/> Changed</button><button onClick={()=>act(memory.id,'archived')}><Archive size={13}/> Archive</button></div></article>})}</div>}</section>
  <section className="future-section future-explainer"><div><div className="section-kicker">THE PROMISE</div><h2>Not another reminder.</h2><p>A reminder says <i>when</i>. A note says <i>where</i>. Afterimage is designed around <strong>when this becomes relevant again</strong>.</p></div><div className="future-flow"><span>MEMORY</span><b>→</b><span>RETURN CONDITION</span><b>→</b><span>CONTEXT</span><b>→</b><span>RELEVANCE</span><b>→</b><span>FEEDBACK</span></div></section>
  {selected&&<div className="inspector-backdrop" onClick={()=>setSelected(null)}><aside className="inspector" onClick={e=>e.stopPropagation()}><button className="inspector-close" onClick={()=>setSelected(null)}><X size={16}/></button><div className="section-kicker">FUTURE SELF REVIEW</div><h3>Is this still true?</h3><p className="inspector-memory">“{selected.text}”</p>{selected.trigger&&<div className="inspect-row"><span>RETURN CONDITION</span><b>{selected.trigger}</b></div>}{selected.why&&<div className="inspect-row"><span>WHY IT MATTERS</span><b>{selected.why}</b></div>}<div className="inspect-row"><span>MEMORY HEALTH</span><b>{memoryHealth(selected).health.toUpperCase()} · {Math.round(memoryHealth(selected).score*100)}%</b></div><button className="inspector-action" onClick={()=>act(selected.id,'confirmed')}><Check size={14}/> Yes — keep this memory</button><button className="inspector-action" onClick={()=>act(selected.id,'outdated')}><X size={14}/> No — this changed</button><button className="inspector-action" onClick={()=>setSelected(null)}>Not sure yet</button></aside></div>}
 </main>
}
